### ISSUE TITLE
Cannot pass PlayerLoginEvent..

### ISSUE THREAD

**Issue by ghost** [funkemunky/Fiona-Anticheat#1]
I was testing this out, and every time I joined, it would say PlayerLoginEvent couldn't be passed.

`> [04:34:02 ERROR]: Could not pass event PlayerLoginEvent to Fiona v3.5.2
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[server.jar:git-Spigot-1a3504a-dfa7583]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[server.jar:git-Spigot-1a3504a-dfa7583]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [server.jar:git-Spigot-1a3504a-dfa7583]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [server.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.PlayerList.attemptLogin(PlayerList.java:531) [server.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:129) [server.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.LoginListener.tick(LoginListener.java:53) [server.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:230) [server.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:119) [server.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:994) [server.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [server.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [server.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [server.jar:git-Spigot-1a3504a-dfa7583]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.util.NoSuchElementException: packet_handler
at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1119) ~[server.jar:git-Spigot-1a3504a-dfa7583]
at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:260) ~[server.jar:git-Spigot-1a3504a-dfa7583]
at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:249) ~[server.jar:git-Spigot-1a3504a-dfa7583]
at com.comphenix.protocol.injector.netty.PipelineProxy.addBefore(PipelineProxy.java:66) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelInjector$3$1.addBefore(ChannelInjector.java:272) ~[?:?]
at com.ngxdev.tinyprotocol.api.TinyProtocol1_8.injectChannelInternal(TinyProtocol1_8.java:371) ~[?:?]
at com.ngxdev.tinyprotocol.api.TinyProtocol1_8.injectPlayer(TinyProtocol1_8.java:345) ~[?:?]
at com.ngxdev.tinyprotocol.api.TinyProtocol1_8$5.onPlayerLogin(TinyProtocol1_8.java:164) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[server.jar:git-Spigot-1a3504a-dfa7583]
... 13 more`

**Comment by ghost** [comment]
@funkemunky

**Comment by ghost** [comment]
Funkemunky mental incapability?!

**Comment by funkemunky** [comment]
This was open sourced as is and isn't being maintained.
